export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_PROFILE = "FETCH_PROFILE";

export const FETCH_FEED = "FETCH_FEED";

export const FETCH_CHILD_PROFILE = "FETCH_CHILD_PROFILE";

export const FETCH_HOMES = "FETCH_HOMES";

export const FETCH_HOME_DETAIL = "FETCH_HOME_DETAIL";

export const ADD_CHILD = "ADD_CHILD";
